builders:
  automation_key_generator:
    import: "package:testsweets_generator/builder.dart"
    builder_factories: ["automationKeyGenerator"]
    build_extensions: { "$lib$": ["all_files.txt"] }
    auto_apply: dependents
    build_to: source
