name: testsweets
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/FilledStacks/testsweets

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.1

dev_dependencies:
